# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
	source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

. $HOME/.shell_exports
. $HOME/.shell_functions
. $HOME/.shell_aliases

if [ -f $HOME/.shell_extra ]; then
	. $HOME/.shell_extra
fi

# fzf
if [ -e ~/.fzf ]; then
	_append_to_path ~/.fzf/bin
	source ~/.fzf/shell/key-bindings.zsh
	source ~/.fzf/shell/completion.zsh
fi

# fzf + ag configuration
if _has fzf && _has ag; then
  export FZF_DEFAULT_COMMAND='ag --nocolor -g ""'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND"
fi
