image: debian:jessie

before_script: 
    - apt-get update -y && apt-get install -y vim git

build:
    stage: build
    script:
        - echo yes | ./bootstrap.sh
        - vim +PluginInstall +qall

test:
    stage: test
    script:
        - ./test.sh
